name: Android Release Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/my-release-key.jks

      - name: Verify file exists
        run: ls -la android/app

      - name: Verify file type
        run: file android/app/my-release-key.jks

      - name: Validate keystore
        run: |
          keytool -list -v \
            -keystore android/app/my-release-key.jks \
            -storepass "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}"
            
      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build Release APK
        run: |
          cd android
          ./gradlew assembleRelease \
            -PINDOMINUSAPP_UPLOAD_STORE_FILE=my-release-key.jks \
            -PINDOMINUSAPP_UPLOAD_STORE_PASSWORD=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
            -PINDOMINUSAPP_UPLOAD_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }} \
            -PINDOMINUSAPP_UPLOAD_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk